name: Key Test

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        steps:
            - name: Set up SSH key
              run: |
                  echo "$SSH_PRIVATE_KEY" > id_rsa
                  chmod 600 id_rsa
                  eval $(ssh-agent -s)
                  ssh-add id_rsa
                  ssh -o StrictHostKeyChecking=no -i id_rsa $SSH_USERNAME@$VM_IP "service LastSeenDemo restart"
            
